apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: khan-system
  name: controller
spec:
  selector:
    matchLabels:
      app: khan
      tier: controller
      version: 1.0.0-SNAPSHOT-LOCAL-2
  template:
    metadata:
      labels:
        app: khan
        tier: controller
        version: 1.0.0-SNAPSHOT-LOCAL-2
    spec:
      serviceAccount: khan-controller
      containers:
      - name: controller
        image: docker-registry.aeg.cloud/khan-system/controller:1.1.0-SNAPSHOT-LOCAL-1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 1Gi
            cpu: 500m
        env:
        - name: SERVER_SSL_ENABLED
          value: "false"
        - name: SERVER_PORT
          value: ":8080"
        ports:
        - containerPort: 8080
          protocol: TCP