apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: khan-system
  name: agent
spec:
  selector:
    matchLabels:
      app: khan
      tier: agent
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/path: "/connections"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
        prometheus.io/scrape: "true"
      labels:
        app: khan
        tier: agent
        version: v1
    spec:
      containers:
      - name: agent
        image: docker-registry.aeg.cloud/khan-system/agent:1.0.0-SNAPSHOT-LOCAL-15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SERVER_PORT
          value: ":8080"
        - name: SERVER_SSL_ENABLED
          value: "false"
        - name: APPMAPPING_URL
          value: "http://controller/appmapping"
        - name: CONNTRACK_SCRIPT
          value: "/tmp/connscript/conntrackScript.sh"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: conntrack
          mountPath: /tmp/conntrack
        - name: khan-script
          mountPath: /tmp/connscript/conntrackScript.sh
          subPath: conntrackScript.sh
        resources:
          limits:
            memory: 256Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: 500m
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: conntrack
        hostPath:
          path: /proc/net
      - name: khan-script
        configMap:
          name: khan-script
          defaultMode: 493
