apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: khan-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: khan-registry
subjects:
- kind: ServiceAccount
  name: khan-registry
  namespace: khan-system