apiVersion: v1
kind: Service
metadata:
  namespace: khan-system
  name: khan-registry
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: khan-registry
