apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: khan-system
  name: khan-agent
spec:
  selector:
    matchLabels:
      app: khan-agent
  template:
    metadata:
      annotations:
        prometheus.io/path: "/khan"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
        prometheus.io/scrape: "true"
      labels:
        app: khan-agent
    spec:
      containers:
      - name: agent
        image: your-registry.com/khan-system/khan-agent:v1.1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SERVER_PORT
          value: ":8080"
        - name: REGISTRY_URL
          value: "http://khan-registry/cache"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 256Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: 500m
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
